# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        PetFoodShoppingBasketBundle\Entity\User:
            algorithm: bcrypt


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: PetFoodShoppingBasketBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                provider: our_db_provider
                login_path: user_login
                check_path: user_login
            logout:
                path: /logout
                target: /login
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/product/manage, roles: [ ROLE_ADMIN ] }
        - { path: ^/, roles: [ ROLE_USER, ROLE_ADMIN, ROLE_EDITOR ] }