# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

# src/PetFoodShoppingBasketBundle/Resources/config/services.yml
services:
    repo.promotions:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
          - \PetFoodShoppingBasketBundle\Entity\Promotion
    promotion_manager:
        class: PetFoodShoppingBasketBundle\Service\PromotionManager
        arguments: ['@repo.promotions']
    price_calculator:
        class: PetFoodShoppingBasketBundle\Service\PriceCalculator
        arguments: ['@promotion_manager']
    cart_calculator:
        class: PetFoodShoppingBasketBundle\Service\CartCalculator
        arguments: ['@doctrine.orm.entity_manager', getRepository]

