# src/PetFoodShoppingBasketBundle/Resources/config/services.yml
services:
    price_calculator:
        class: PetFoodShoppingBasketBundle\Service\PriceCalculator
        arguments: ['@doctrine.orm.entity_manager']